---
- name: update apt cache
  apt:
    update_cache: yes

- name: prerequisites for adding telegraf repository
  apt:
    name: 
      - curl
      - gnupg
    state: present

- name: add influxdata gpg key
  ansible.builtin.command: >
    curl -fsSL https://repos.influxdata.com/influxdata-archive_compat.key
    -o /etc/apt/keyrings/influxdata-archive_compat.key
  args:
    creates: /etc/apt/keyrings/influxdata-archive_compat.key

- name: add influxdata repository
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/influxdata.list
    content: "deb [signed-by=/etc/apt/keyrings/influxdata-archive_compat.key] https://repos.influxdata.com/ubuntu stable main"
    owner: root
    group: root
    mode: '0644'

- name: update apt cache for new repository
  apt:
    update_cache: yes

- name: install telegraf
  apt:
    name: telegraf
    state: present
  register: result
  until: result is succeeded
  retries: 20
  delay: 10

- name: prerequisites for telegraf-geoip
  apt:
    name: 
      - golang-go
    state: present

- name: clone telegraf-geoip repo
  ansible.builtin.git:
    repo: https://github.com/a-bali/telegraf-geoip
    dest: /root/telegraf-geoip

- name: build telegraf-geoip
  ansible.builtin.shell: |
    cd /root/telegraf-geoip
    go build -o geoip cmd/main.go

- name: copy telegraf-geoip to /usr/local/bin
  ansible.builtin.command:
    cmd: cp /root/telegraf-geoip/geoip /usr/local/bin/

- name: set permissions for telegraf-geoip
  ansible.builtin.command:
    cmd: chmod 755 /usr/local/bin/geoip

# Retry logic for other package installations
- name: install packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - nginx
    - graphviz
    - heaptrack
    - jq
    - python3
    - python3-pip
    - ripgrep
    - zip
  register: result
  until: result is succeeded
  retries: 20
  delay: 10

- name: Install boto3
  ansible.builtin.command: pip3 install boto3 --prefix /usr

