---
- name: copy service file
  become: True
  template:
    src: sn_node.service.j2
    dest: /etc/systemd/system/safenode@{{ item }}.service
  register: service_template_created

- name: reload the system manager configuration
  become: True
  command: systemctl daemon-reload
  when: service_template_created.changed

- name: start the node services
  become: True
  systemd:
    name: safenode@{{ item }}
    state: started